# <center>Combining Data(SQL Joins in Pandas)

**The Big Picture**\
Multiple DataFrames --> Combine them --> Analyze Everything Together\
**The Three Major Tools**\
Pandas provides:\
pd.concat()\
pd.merge()\
df.join()

**1. pd.concat() - Stacking Data**\
Put things on top of each other\
OR\
Put things beside each other

**Vertical Concatenation (axis = 0)**

In [18]:
import pandas as pd
df1 = pd.DataFrame({
    "Name":["Ali","Sara"],
    "Age":[23,25]
        })
df2 = pd.DataFrame({
    "Name":["Bilal","Shama"],
    "Age":[26,27]
})
combined = pd.concat([df1,df2])
combined

    Name  Age
0    Ali   23
1   Sara   25
0  Bilal   26
1  Shama   27

Notice: Indexes repitition is weird, isn't it?

**ignore_index=True**

In [2]:
combined = pd.concat(
    [df1,df2],
    ignore_index=True
)
combined

    Name  Age
0    Ali   23
1   Sara   25
2  Bilal   26
3  Shama   27

Feels good now!

**Horizontal Concatenation(axis = 1)**

In [4]:
names = pd.DataFrame({
    "Name":["Ali","Ahmed"]
})
ages = pd.DataFrame({
    "Age":[23,24]
})
salaries = pd.DataFrame({
    "Salary":[55000,75000]
})
df = pd.concat(
    [names,ages,salaries],
    axis=1
)
df

    Name  Age  Salary
0    Ali   23   55000
1  Ahmed   24   75000

axis=0 --> stack rows --> Vertical\
axis=1 --> stack columns --> Horizontal

**3. pd.merge()**\
The Syntax:\
pd.merge(\
left_df,\
right_df,\
on="common_column"\
)

In [10]:
customers = pd.DataFrame({
    "CustomerID":[1,2,3],
    "Name":["Ali","Sara","Ahmed"]
})
orders = pd.DataFrame({
    "CustomerID":[1,2,1,4],
    "Product":["Laptop","Phone","Mouse","Keyboard"]
})

In [12]:
merged = pd.merge(
    customers,
    orders,
    on = "CustomerID"
)
merged

   CustomerID  Name Product
0           1   Ali  Laptop
1           1   Ali   Mouse
2           2  Sara   Phone

**Inner Join : Keep ONLY matching rows like above**

Next is:\
**Left Join : Keep all from the left df even if it deosn't exist in right**

In [13]:
left = pd.merge(
    customers,
    orders, 
    on="CustomerID",
    how="left"
)
left

   CustomerID   Name Product
0           1    Ali  Laptop
1           1    Ali   Mouse
2           2   Sara   Phone
3           3  Ahmed     NaN

**Right Join: Keep all from the right df even if it doesn't exist in left**

In [14]:
right = pd.merge(
    customers,
    orders,
    on = "CustomerID",
    how = "right"
)
right

   CustomerID  Name   Product
0           1   Ali    Laptop
1           2  Sara     Phone
2           1   Ali     Mouse
3           4   NaN  Keyboard

**Outer Join : Keep EVERYTHING**

In [15]:
outer = pd.merge(
    customers,
    orders,
    on = "CustomerID",
    how = "outer"
)
outer

   CustomerID   Name   Product
0           1    Ali    Laptop
1           1    Ali     Mouse
2           2   Sara     Phone
3           3  Ahmed       NaN
4           4    NaN  Keyboard

**Dealing with different column names**

In [16]:
customers = pd.DataFrame({
    "CustomerID":[1,2,3],
    "Name":["Ali","Sara","Ahmed"]
})
orders = pd.DataFrame({
    "CustID":[1,2,1,4],
    "Product":["Laptop","Phone","Mouse","Keyboard"]
})

In above example,\
customers --> CustomerID\
orders --> CustID

In [17]:
merged = pd.merge(
    customers,
    orders,
    left_on = "CustomerID",
    right_on = "CustID"
)
merged

   CustomerID  Name  CustID Product
0           1   Ali       1  Laptop
1           1   Ali       1   Mouse
2           2  Sara       2   Phone

**Dealing with Multiple Keys**

In [19]:
df1 = pd.DataFrame({
    "Name":["Ali","Sara"],
    "Age":[23,25],
    "Department":['HR','IT'],
    "Gender":["M","F"]
        })
df2 = pd.DataFrame({
    "Name":["Bilal","Shama"],
    "Age":[26,27],
    "Department":['Finance','IT'],
    "Gender":["M","F"]
})

**Updating Suffixes**

In [23]:
multi_keys = pd.merge(
    df1,
    df2,
    on = ["Department","Gender"],
    how = "outer",
    suffixes = ("_left","_right")
)
multi_keys

  Name_left  Age_left Department Gender Name_right  Age_right
0       NaN       NaN    Finance      M      Bilal       26.0
1       Ali      23.0         HR      M        NaN        NaN
2      Sara      25.0         IT      F      Shama       27.0

**Indicator Column : useful for debugging joins**

In [25]:
pd.merge(

    customers,

    orders,

    left_on = "CustomerID",
    right_on = "CustID",

    how="outer",

    indicator=True
)

   CustomerID   Name  CustID   Product      _merge
0         1.0    Ali     1.0    Laptop        both
1         1.0    Ali     1.0     Mouse        both
2         2.0   Sara     2.0     Phone        both
3         3.0  Ahmed     NaN       NaN   left_only
4         NaN    NaN     4.0  Keyboard  right_only

**3. join()**

join() works on indexes\
Professionals generally prefer pd.merge() because it's more explicit.